### ISSUE TITLE
Internal Server Error when publishing shipment in zenodo sandbox

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-shipper#39]
When trying to publish a shipment in zenodo sandbox I receive an `Internal Server Error`. 
Here the complete error message:
```
Error: 500 Internal Server Error
Sorry, the requested URL "http://localhost/api/v1/shipment/asdfasdf-209c-4753-8c1d-170cbe2eba8c/publishment"
               caused an error:
     Internal Server Error
     Exception:
              TypeError("publish() missing 1 required positional argument: 'token'")
              Traceback:
              Traceback (most recent call last):
              File "/usr/local/lib/python3.6/site-packages/bottle.py", line 862, in _handle
                    return route.call(**args)
              File "/usr/local/lib/python3.6/site-packages/bottle.py", line 1740, in wrapper
                    rv = callback(*a, **ka)
              File "shipper.py", line 168, in shipment_put_publishment
                    REPO_TARGET.publish(REPO_TOKEN)
              TypeError: publish() missing 1 required positional argument: "token"
```

**Comment by ghost** [comment]
I fixed this in order to make publishments possible for zenodo and zenodo sandbox at all, but the response of that put request is temporarily disabled because it requires some restructuring to have the shipper pipe through zenodo api responses as real http responses of its own api as well as store the publication status in db from out the repo class. 
In the meantime the actual publishment works.
